### ISSUE TITLE
Sticky error box - Needs to display when error occurs while inserting an image

### ISSUE THREAD

**Issue by bwbaker1** [NASA-IMPACT/nasa-apt-frontend#403]
@wrynearson @naomatheus @deborahUAH 

### Description: 
User error messages are timed and do not last long enough to read (per user feedback). 

### Tasks:
- [ ] Implement a fix so that the current error messages becomes sticky (i.e., do not disappear) until a user clicks on the message (x in top right corner of box)

### Acceptance Criteria: 
- [ ] Sticky error messages appear when the user encounters an error (e.g., trying to upload image in unsupported format)
- [ ] Frontend tested to ensure error messages are sticky and do not disappear until user clicks to remove it.

## Example: 
The error message below disappears after a few seconds.  Instead, it should remain until a user selects to remove it.

![Image](https://user-images.githubusercontent.com/56319064/212091708-fbbba0f5-15b0-434d-b49a-67c083fede56.png)

**Comment by wrynearson** [comment]
I will spec this out for @kamicut

**Comment by kamicut** [comment]
@wrynearson should this be for all error boxes? From what I've read, I think this is simply an option to include in each of the "toast" component's instantiations.

**Comment by deborahUAH** [comment]
The error box should be sticky and require user click to remove for any error box that needs to be read so the user can make a change in their behavior

**Comment by wrynearson** [comment]
Sorry @kamicut for my slow reply. Process, success, and error toasts should behave the same way across the site. There are some inconsistencies at the moment. I would encourage that we follow best practices/default behavior where possible.

@deborahUAH I raised this with some designers at DevSeed. They thought that error toasts (messages in the bottom right corner) should be time based, and not sticky, for the following reasons:
1. Most of the error toasts are notifying of events and do not require users to act _in a different way_ than they did previously.
2. Static toasts sometimes no longer make sense if the page is changed (e.g., MFA code -> dashboard)
3. Static toasts can have more than one present. The act of manually clicking on 3+ toasts to go away can be more annoying to the user than the actual error.

**Comment by deborahUAH** [comment]
I agree with consistency in toast behavior.  What are the best practices for toasts ?  The time that some have is too quick. Remove un-needed toasts that have resulted from changes (MFA).

**Comment by kamicut** [comment]
Toasts on the site have a default behavior. We use the `createProcessToast` with the default settings: 
- on success, auto-close the toast after 3 seconds
- on failure, close the toast when the user dismisses it

There are a few places in the application that I could find where toasts don't use `createProcessToast`:
- [ ] Max number of columns in a table error: https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/b0ca7a64cf32873612c66a960a0b77d963c50715/app/assets/scripts/components/slate/plugins/table/index.js#L62-L63
- [ ] Error Locking the ATBD version https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/b0ca7a64cf32873612c66a960a0b77d963c50715/app/assets/scripts/components/documents/single-edit/check-lock.js#L73
- [ ] "We have recovered data" toast https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/b0ca7a64cf32873612c66a960a0b77d963c50715/app/assets/scripts/components/documents/single-edit/local-store/index.js#L49 (Although this one might need some special handling)
- [ ] Import reference toast https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/b0ca7a64cf32873612c66a960a0b77d963c50715/app/assets/scripts/components/documents/single-edit/step-references/references-import.js#L57
- [ ] Image upload toast https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/b0ca7a64cf32873612c66a960a0b77d963c50715/app/assets/scripts/components/slate/plugins/image/toolbar-image-button.js#L53

I think if we fix these then we would bringing consistency by having all the toasts use the common toast component settings.

**Comment by wrynearson** [comment]
Thanks @kamicut for the review! Could you go ahead and change these where it makes sense to `createProcessToast`? 

FYI, for the recover data toast, we have slightly different behavior where the user can choose to restore or disregard the data.

<img width="380" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/25919630/2f3baf63-a389-473a-97ee-4d98b112ab3c">

**Comment by wrynearson** [comment]
@bwbaker1, I think a few issues related to error toasts are getting mixed up between tickets. Here are the issues I'm seeing:

- [ ] Toast behavior should be consistent
    - @kamicut's PR https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/481 addresses this.
    - Please note that we've set error toasts to be _not sticky_, and instead _time-based_. This is based on feedback from our designers and team members for best practices. If we think error toasts should in fact be sticky, we can easily change them (we have a way now to control behavior of all toasts of the same type)
- [ ] Error toast clears too quickly when users try to upload valid images >6mb.
    - This is different than the toast behavior being consistent. This is a separate bug that we'll investigate.

**Comment by bwbaker1** [comment]
@wrynearson I think time-based is fine, especially if this is considered a best practice. I agree with the above comments that clicking out of toasts can be annoying. We will get these tested asap for consistency and to make sure there is enough time to read all errors messages. Thanks.

Thanks for the heads up about the image upload toast.

**Comment by wrynearson** [comment]
Thanks @bwbaker1. I think this is safe to bring to production today, but if you disagree, please let me know. It will be easier to deploy everything that's on staging currently (this included) rather than having to cherry-pick what to deploy, but we can do that if needed

**Comment by bwbaker1** [comment]
@wrynearson Let's go ahead and deploy.
